### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by flure** [defold/extension-admob#3]
On Linux, when trying to build-and-launch for dmengine on Android, I get this error message:

`Build server output: Unsupported platform x86_64-linux	ext.manifest	/testadmob/content/admob	Unknown	Problem`

**Comment by flure** [comment]
I have more info on this bug. I can finally build but with a few steps :
1) don't include admob as a library, but add the `admob` directory to the project (as stated in issue #2)
2) as I'm building only for Android (for the moment), I removed ext.manifest, and the `/admob/lib/ios` directory

Now I can build and launch on dmengine on Android, but it will be a problem when I want to make an iOS version.

**Comment by mathiaswking** [comment]
HI!
Regarding your first comment, I'm a bit confused. "Build and launch" refers to building a build for the current host platform (in your case linux). Since we don't support linux yet for native extensions, this will not work. Secondly, you mention android, which suggests that you chose to bundle for android. That should have worked (although I haven't tested it from a linux machine).

Support for linux builds will come very soon (in a couple of weeks I hope)
In the meantime, I'll look into why you can't bundle android builds from linux.

**Comment by flure** [comment]
Hi
Of course it doesn't make any sense (AFAIK) to test admob on linux :)
I'm launching dmengine on my Android phone, and then in defold I select my phone as the target, and use "Build and Launch" to build it and launch it directly on my phone. (I'm not creating a bundle).
(I hope I explain well enough...)
This process always worked before I tried to add admob...

**Comment by flure** [comment]
I also tried to make an Android bundle but had the same problem. It looks like, although building for Android, the building process uses the iOS resources as well.

**Comment by AGulev** [comment]
[New implementation of AdMob SDK from scratch released](https://github.com/defold/extension-admob/releases/tag/2.0.0)
